### ISSUE TITLE
Favour number of assigned cores

### ISSUE THREAD

**Issue by ljocha** [RECETOX/apLCMS#2]
All available cores are always used, which results in overloading worker node and poor performance when multiple such jobs are scheduled there.

The wrapper must read GALAXY_SLOTS env variable (if set) and propagate it to parallel::makeCluster() in the R script.

**Comment by martenson** [comment]
@ljocha did you see this locally or on UMSA? Proper Slurm configuration should not allow using all cores.

**Comment by ljocha** [comment]
> @ljocha did you see this locally or on UMSA? Proper Slurm configuration should not allow using all cores.

On UMSA. AFAIK Slurm (at least in our configuration) does not use cgroups or similar resource restrictions, it just counts the number of cores the jobs _claim_ to use. It can't prevent misbehaving jobs to use more.

If you run apLCMS on UMSA, it spawns 16 R processes on the 8 core node (this is due to bug in R's detectCores() on linux). So far we can pretend that hyperthreading saves us (though it's not entirely true).

If you run two instances of apLCMS, they both end up on the same worker (fine from Slurm's point of view), and its load grows unacceptably. The competing processes run terribly slow, then.

**Comment by martenson** [comment]
I confirm the issue, we tested with @ondrejme  just now on UMSA.

@ljocha please see the root of the problem at https://github.com/RECETOX/galaxytools/pull/41#issuecomment-729687522

>On UMSA. AFAIK Slurm (at least in our configuration) does not use cgroups or similar resource restrictions, it just counts the number of cores the jobs claim to use. It can't prevent misbehaving jobs to use more.

Galaxy decorates job submissions with slurm native specification here: https://gitlab.ics.muni.cz/recetox/mass-spectrometry/umsa-galaxy/-/blob/im_slurm/files/galaxy/config/job_conf.xml#L13

edit: I do not know the details how Slurm internally enforces the given specification, but I thought it does. I am somewhat shaken in that belief now.

**Comment by ljocha** [comment]
Bad news. "docker run --cpus NN" does not actually work in this case:

```
$ docker run -ti --cpus 2 rocker/r-ver:4.0.0 bash

# cat /proc/cpuinfo | grep processor | tail -1
processor	: 23

# R
...
> parallel::detectCores()
[1] 24
```

In other words, docker limits the _usage_ of cpu cores (probably) but it does not change the hardware visibility. 

Consequently, at UMSA nodes, we will end up with each apLCMS instance running with 16 processes (= # of logical cores) with docker throttling them to just few cores (GALAXY_SLOTS setting). This would bring terrible performance impact, we need to pass the GALAXY_SLOTS environment variable down into the docker container and using it in the call of apLCMS::unsupervised()

**Comment by martenson** [comment]
> we need to pass the GALAXY_SLOTS environment variable down into the docker container and using it in the call of apLCMS::unsupervised()

This seems to be the best solution for aplcms that acts as the bad citizen here. Making it configurable is a big improvement.
