### ISSUE TITLE
Verify content of HDF file output

### ISSUE THREAD

**Issue by hechth** [RECETOX/apLCMS#7]
![image](https://user-images.githubusercontent.com/12066490/99670449-d8fb8c80-2a70-11eb-96da-595bd433027d.png)

The file content seems to be a bit disorganized, so the data is not visible as an array and can for example not be exported to a text file. Can you confirm that this is because of the viewer and not because of the stored data?

Attached find the apLCMS output file.
[Galaxy22-[apLCMS_-_Unsupervised_on_data_20,_data_19,_and_others].zip](https://github.com/RECETOX/apLCMS/files/5566915/Galaxy22-.apLCMS_-_Unsupervised_on_data_20._data_19._and_others.zip)

**Comment by xtracko** [comment]
Resolved over the Tems chat. The output files are fine, only the export functionality of the 3rd party tool HDFView is broken. Suggested exporting to `csv` with Pandas.

```python
pandas.read_hdf("path/to/file.h5", "internal_hdf_path_to_the_table").to_csv("path/to/file.csv")
```
